CREATE DATABASE DB_produtos;
USE DB_produtos;
CREATE TABLE CONSUMIDOR (
    ID_CONSUMIDOR INT NOT NULL, 
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    ENDEREÇO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CONSUMIDOR PRIMARY KEY(ID_CONSUMIDOR)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    PRECO_UNITARIO NUMERIC(10,2) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO)
);

CREATE TABLE COMPRADOS (
    ID INT NOT NULL,
    ID_CONSUMIDOR INT NOT NULL,
    DATA_COMPRA TIMESTAMP NOT NULL,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL,
    CONSTRAINT PK_COMPRADOS PRIMARY KEY(ID),
    CONSTRAINT FK_COMPRADOS_CONSUMIDOR FOREIGN KEY (ID_CONSUMIDOR) 
        REFERENCES CONSUMIDOR(ID_CONSUMIDOR)
);

CREATE TABLE PRODUTOSCOMPRADOS (
    ID_COMPRA INT NOT NULL,
    COMPRA_ID INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    CONSTRAINT PK_PRODUTOSCOMPRADOS PRIMARY KEY(ID_COMPRA),
    CONSTRAINT FK_PRODUTOSCOMPRADOS_COMPRA FOREIGN KEY (COMPRA_ID) 
        REFERENCES COMPRADOS(ID),
    CONSTRAINT FK_PRODUTOSCOMPRADOS_PRODUTO FOREIGN KEY (ID_PRODUTO) 
        REFERENCES PRODUTO(ID_PRODUTO)
);